### ISSUE TITLE
Doesn't work in Progressive Web App

### ISSUE THREAD

**Issue by KeepAustinWired** [gerbus/chrome-google-calendar-meeting-start-times#3]
This works great, but I noticed that it doesn't work when I have Google Calendar running as a [Progressive Web App](https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DDesktop). All my other extensions work in the PWA. Would be great if this one did too!

**Comment by KeepAustinWired** [comment]
Appears to work in the PWA now. I don't know what changed, but my colleague and I both noticed it works now.

**Comment by KeepAustinWired** [comment]
Appears to work in the PWA now. I don't know what changed, but my colleague and I both noticed it works now.

**Comment by gerbus** [comment]
Weird, I didn't do anything on my end. Glad it works now.
